### ISSUE TITLE
文档中针对 Windows 7 的安装说明存在未提及的问题

### ISSUE THREAD

**Issue by hxabcd** [ClassIsland/classisland-docs-next#2]
本人在 Windows 7 系统中按照 教程 - 安装与开始 - 在 Windows 7 中安装 ClassIsland 所述操作，在未安装 KB3063858 补丁的情况下成功运行了 ClassIsland，然而希沃白板却出现了打不开的情况，甚至卸载程序都无法启动。经反复排查，发现只要删除教程中创建的 `DOTNET_GCName` `DOTNET_EnableWriteXorExecute ` 两个环境变量即可正常启动希沃白板。目前不确定此问题是否因未安装 KB3063858 补丁引起，仍待后续测试。望能够在文档中加上相应的后果或说明。

问题已通过升级至 Windows 10 解决。但仍建议向文档中添加说明以避免此类情况再次发生

**Comment by hxabcd** [comment]
其实主要是给后人留个提醒，不至于查半天，毕竟我已经把系统升级成win10了，也不存在问题了
至于为什么没装补丁，是因为下载后安装报错，但是程序能运行（可能能够跑起来也只是个假象）

**Comment by hxabcd** [comment]
问题已通过升级至 Windows 10 解决。但仍建议向文档中添加说明以避免此类情况发生

**Comment by hello8693DSZ** [comment]
文档已修改。请等待 .NET 6 版本发布。
